### ISSUE TITLE
The solution appears to be populated already in the starter code

### ISSUE THREAD

**Issue by bricknet1** [learn-co-curriculum/python-p4-flask-restful-ud#1]
### Canvas Link

https://learning.flatironschool.com/courses/6259/assignments/233481?module_item_id=547408

### Concern

The following is already included in app.py, so the lab is effectively complete for us before we begin. This starts on line 83:

`def patch(self, id):
        record = Newsletter.query.filter_by(id=id).first()
        for attr in request.form:
            setattr(record, attr, request.form[attr])

        db.session.add(record)
        db.session.commit()

        response = make_response(
          record.to_dict(),
          200  
        )

        return response

    def delete(self, id):
        record = Newsletter.query.filter_by(id=id).first()

        db.session.delete(record)
        db.session.commit()

        response_dict = {"message": "record successfully deleted"}

        response = make_response(
            response_dict, 
            200
        )

        return response`

**Comment by professor-ben** [comment]
Thanks for raising this issue! The solution code has been removed from `app.py`.

-Ben
