### ISSUE TITLE
Readability

### ISSUE THREAD

**Issue by abbyesmith** [learn-co-curriculum/python-p4-flask-restful-ud#2]
### Canvas Link

https://learning.flatironschool.com/courses/6267/assignments/236281?module_item_id=554238

### Concern

In general, it would be nice if this phrase:
Run flask db upgrade from the server/ directory

would be reworded to:
Change directories to the server and run flask db upgrade

This would give directions in the correct order instead of giving one direction THEN reminding students to switch into the server as a requirement to follow the direction.

**Comment by professor-ben** [comment]
Hi Abby,

I think this is a good point. I'll make sure to rearrange this instruction when we go through the lessons for the upcoming update to the curriculum.

Thanks,
Ben

**Comment by linda-seiter** [comment]
instructions updated
