### ISSUE TITLE
Problem in seed.py

### ISSUE THREAD

**Issue by SWhalley1130** [learn-co-curriculum/python-p4-flask-restful-ud#3]
### Canvas Link

https://learning.flatironschool.com/courses/6267/assignments/236281?module_item_id=554238

### Concern

When the lesson is forked and cloned, there is an error in the seed.py file. The lesson says to run `pipenv install`, `pipenv shell`, `cd server`, `flask db upgrade`, then `python seed.py`. The last functional command is `flask db upgrade`, which will create the tables properly. When seed.py is ran thereafter, the program as a runtime error. 

![image](https://user-images.githubusercontent.com/98498031/230248589-049ff84b-234b-46bd-900c-3289cb31ac1a.png)

### Suggested Changes

Delete db.init_app(app) on line 8 in seed.py. The database will seed properly after that. 
![image](https://user-images.githubusercontent.com/98498031/230249134-b594d214-cfed-47af-a493-5ce9f9de44a2.png)

**Comment by pgill97** [comment]
Removed db.init_app(app)  from seed and debug file in both main and solution branch.
